# Generated by Django 4.2.5 on 2023-10-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookReview', '0002_review_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes_count',
        ),
    ]
