# Generated by Django 4.2.6 on 2023-10-31 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlist',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_readlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
