# Generated by Django 4.2.4 on 2023-10-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_likes'),
        ('main', '0002_user_book_description_book_genre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='readlist',
            name='books',
            field=models.ManyToManyField(blank=True, to='book.book'),
        ),
    ]
