# Generated by Django 4.2.5 on 2023-10-29 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_book_description_book_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.DeleteModel(
            name='Readlist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
