# Generated by Django 4.2.4 on 2023-10-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_book_alter_readlist_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readlist',
        ),
    ]
