# Generated by Django 4.2.6 on 2023-10-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_book_alter_readlist_books'),
        ('main', '0003_remove_book_description_remove_book_genre_and_more'),
    ]

    operations = [
    ]
