# Generated by Django 4.2.4 on 2023-11-26 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('number_of_reviews', models.IntegerField(blank=True, null=True)),
                ('book_description', models.TextField(blank=True, null=True)),
                ('image_link', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('bookmarked_by', models.ManyToManyField(blank=True, related_name='bookmarked_books', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
