# Generated by Django 4.2.4 on 2023-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('numberOfReviews', models.IntegerField(blank=True, null=True)),
                ('bookDescription', models.TextField(blank=True, null=True)),
                ('imageLink', models.CharField(blank=True, max_length=255, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
