# Generated by Django 4.2.4 on 2023-10-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookDescription',
            new_name='book_description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='numberOfReviews',
            new_name='number_of_reviews',
        ),
        migrations.RemoveField(
            model_name='book',
            name='imageLink',
        ),
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
