<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-29 03:29
=======
# Generated by Django 4.2.4 on 2023-10-28 14:21
>>>>>>> ac7699fb7ad89aee271404973718fe1658eaed1d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_merge_20231028_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
