# Generated by Django 4.2.6 on 2023-10-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_bookmarked_by_book_liked_by'),
        ('book', '0010_alter_book_bookmarked_by_alter_book_liked_by'),
    ]

    operations = [
    ]
