# Generated by Django 4.2.6 on 2023-10-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_likes'),
        ('user_profile', '0002_book_bookmarked_book_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_reviews',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
