# Generated by Django 4.2.6 on 2023-10-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_bookmarkedbook_likedbook_user_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_name',
        ),
    ]
